### ISSUE TITLE
probability bug

### ISSUE THREAD

**Issue by kyyongh** [gugarosa/learnergy#15]
When I use GaussianRBM to run rbm_classification.py on GPU, these errors appear.

 11%|█         | 51/469 [00:01<00:07, 58.24it/s]C:/cb/pytorch_1000000000000/work/aten/src\ATen/native/cuda/DistributionTemplates.h:591: block: [6,0,0], thread: [416,0,0] Assertion `0 <= p4 && p4 <= 1` failed.
C:/cb/pytorch_1000000000000/work/aten/src\ATen/native/cuda/DistributionTemplates.h:591: block: [6,0,0], thread: [417,0,0] Assertion `0 <= p4 && p4 <= 1` failed.
C:/cb/pytorch_1000000000000/work/aten/src\ATen/native/cuda/DistributionTemplates.h:591: block: [6,0,0], thread: [418,0,0] Assertion `0 <= p4 && p4 <= 1` failed.
C:/cb/pytorch_1000000000000/work/aten/src\ATen/native/cuda/DistributionTemplates.h:591: block: [6,0,0], thread: [419,0,0] Assertion `0 <= p4 && p4 <= 1` failed.
C:/cb/pytorch_1000000000000/work/aten/src\ATen/native/cuda/DistributionTemplates.h:591: block: [6,0,0], thread: [420,0,0] Assertion `0 <= p4 && p4 <= 1` failed.
C:/cb/pytorch_1000000000000/work/aten/src\ATen/native/cuda/DistributionTemplates.h:591: block: [6,0,0], thread: [421,0,0] Assertion `0 <= p4 && p4 <= 1` failed.
C:/cb/pytorch_1000000000000/work/aten/src\ATen/native/cuda/DistributionTemplates.h:591: block: [6,0,0], thread: [422,0,0] Assertion `0 <= p4 && p4 <= 1` failed.
C:/cb/pytorch_1000000000000/work/aten/src\ATen/native/cuda/DistributionTemplates.h:591: block: [6,0,0], thread: [423,0,0] Assertion `0 <= p4 && p4 <= 1` failed.
C:/cb/pytorch_1000000000000/work/aten/src\ATen/native/cuda/DistributionTemplates.h:591: block: [6,0,0], thread: [424,0,0] Assertion `0 <= p4 && p4 <= 1` failed.
C:/cb/pytorch_1000000000000/work/aten/src\ATen/native/cuda/DistributionTemplates.h:591: block: [6,0,0], thread: [425,0,0] Assertion `0 <= p4 && p4 <= 1` failed.
C:/cb/pytorch_1000000000000/work/aten/src\ATen/native/cuda/DistributionTemplates.h:591: block: [6,0,0], thread: [426,0,0] Assertion `0 <= p4 && p4 <= 1` failed.
C:/cb/pytorch_1000000000000/work/aten/src\ATen/native/cuda/DistributionTemplates.h:591: block: [6,0,0], thread: [427,0,0] Assertion `0 <= p4 && p4 <= 1` failed.
C:/cb/pytorch_1000000000000/work/aten/src\ATen/native/cuda/DistributionTemplates.h:591: block: [6,0,0], thread: [428,0,0] Assertion `0 <= p4 && p4 <= 1` failed.
C:/cb/pytorch_1000000000000/work/aten/src\ATen/native/cuda/DistributionTemplates.h:591: block: [6,0,0], thread: [429,0,0] Assertion `0 <= p4 && p4 <= 1` failed.
C:/cb/pytorch_1000000000000/work/aten/src\ATen/native/cuda/DistributionTemplates.h:591: block: [6,0,0], thread: [430,0,0] Assertion `0 <= p4 && p4 <= 1` failed.
C:/cb/pytorch_1000000000000/work/aten/src\ATen/native/cuda/DistributionTemplates.h:591: block: [6,0,0], thread: [431,0,0] Assertion `0 <= p4 && p4 <= 1` failed.
C:/cb/pytorch_1000000000000/work/aten/src\ATen/native/cuda/DistributionTemplates.h:591: block: [6,0,0], thread: [432,0,0] Assertion `0 <= p4 && p4 <= 1` failed.
C:/cb/pytorch_1000000000000/work/aten/src\ATen/native/cuda/DistributionTemplates.h:591: block: [6,0,0], thread: [433,0,0] Assertion `0 <= p4 && p4 <= 1` failed.
C:/cb/pytorch_1000000000000/work/aten/src\ATen/native/cuda/DistributionTemplates.h:591: block: [6,0,0], thread: [434,0,0] Assertion `0 <= p4 && p4 <= 1` failed.
C:/cb/pytorch_1000000000000/work/aten/src\ATen/native/cuda/DistributionTemplates.h:591: block: [6,0,0], thread: [435,0,0] Assertion `0 <= p4 && p4 <= 1` failed.
C:/cb/pytorch_1000000000000/work/aten/src\ATen/native/cuda/DistributionTemplates.h:591: block: [6,0,0], thread: [436,0,0] Assertion `0 <= p4 && p4 <= 1` failed.
C:/cb/pytorch_1000000000000/work/aten/src\ATen/native/cuda/DistributionTemplates.h:591: block: [6,0,0], thread: [437,0,0] Assertion `0 <= p4 && p4 <= 1` failed.
C:/cb/pytorch_1000000000000/work/aten/src\ATen/native/cuda/DistributionTemplates.h:591: block: [6,0,0], thread: [438,0,0] Assertion `0 <= p4 && p4 <= 1` failed.
C:/cb/pytorch_1000000000000/work/aten/src\ATen/native/cuda/DistributionTemplates.h:591: block: [6,0,0], thread: [439,0,0] Assertion `0 <= p4 && p4 <= 1` failed.
C:/cb/pytorch_1000000000000/work/aten/src\ATen/native/cuda/DistributionTemplates.h:591: block: [6,0,0], thread: [440,0,0] Assertion `0 <= p4 && p4 <= 1` failed.
C:/cb/pytorch_1000000000000/work/aten/src\ATen/native/cuda/DistributionTemplates.h:591: block: [6,0,0], thread: [441,0,0] Assertion `0 <= p4 && p4 <= 1` failed.
C:/cb/pytorch_1000000000000/work/aten/src\ATen/native/cuda/DistributionTemplates.h:591: block: [6,0,0], thread: [442,0,0] Assertion `0 <= p4 && p4 <= 1` failed.
C:/cb/pytorch_1000000000000/work/aten/src\ATen/native/cuda/DistributionTemplates.h:591: block: [6,0,0], thread: [443,0,0] Assertion `0 <= p4 && p4 <= 1` failed.
C:/cb/pytorch_1000000000000/work/aten/src\ATen/native/cuda/DistributionTemplates.h:591: block: [6,0,0], thread: [444,0,0] Assertion `0 <= p4 && p4 <= 1` failed.
C:/cb/pytorch_1000000000000/work/aten/src\ATen/native/cuda/DistributionTemplates.h:591: block: [6,0,0], thread: [445,0,0] Assertion `0 <= p4 && p4 <= 1` failed.
C:/cb/pytorch_1000000000000/work/aten/src\ATen/native/cuda/DistributionTemplates.h:591: block: [6,0,0], thread: [446,0,0] Assertion `0 <= p4 && p4 <= 1` failed.
C:/cb/pytorch_1000000000000/work/aten/src\ATen/native/cuda/DistributionTemplates.h:591: block: [6,0,0], thread: [447,0,0] Assertion `0 <= p4 && p4 <= 1` failed.

RuntimeError: CUDA error: device-side assert triggered

But if I run it on cpu, the error while like this:
RuntimeError: Expected p_in >= 0 && p_in <= 1 to be true, but got false.

It seems like the function hidden_sampling dosen't run correctly.

**Comment by MateusRoder** [comment]
Hello kyyongh,I hope is everything well with you.

Without knowing what is your initialization setup may be difficult to track such an issue.
Even if the lack of additional information, seems that it is something wrong with the temperature parameter (T).
However, if you can attach additional information about the running parameters, we can search the problem.

Best regards,
Mateus.

**Comment by kyyongh** [comment]
Hi Mateus, thank you for replying.

I was running the rbm_classification.py with only change the model to GaussianRBM, keeping the initialization parameters same as the RBM：
model = GaussianRBM(
    n_visible=784,
    n_hidden=128,
    steps=1,
    learning_rate=0.1,
    momentum=0,
    decay=0,
    temperature=1,
    use_gpu=True,
)
and the above mentioned error occurred.

when I use GPU, the error woud  be:
C:/cb/pytorch_1000000000000/work/aten/src\ATen/native/cuda/DistributionTemplates.h:591: block: [5,0,0], thread: [316,0,0] Assertion `0 <= p4 && p4 <= 1` failed.
C:/cb/pytorch_1000000000000/work/aten/src\ATen/native/cuda/DistributionTemplates.h:591: block: [5,0,0], thread: [317,0,0] Assertion `0 <= p4 && p4 <= 1` failed.
C:/cb/pytorch_1000000000000/work/aten/src\ATen/native/cuda/DistributionTemplates.h:591: block: [5,0,0], thread: [318,0,0] Assertion `0 <= p4 && p4 <= 1` failed.
C:/cb/pytorch_1000000000000/work/aten/src\ATen/native/cuda/DistributionTemplates.h:591: block: [5,0,0], thread: [319,0,0] Assertion `0 <= p4 && p4 <= 1` failed.
 12%|█▏        | 56/469 [00:02<00:16, 25.34it/s]
Traceback (most recent call last):
  File "E:\Document\机器学习\GitRepository\learnergy\examples\applications\bernoulli\rbm_classification.py", line 43, in <module>
    model.fit(train, batch_size=batch_size, epochs=1)
  File "E:\Document\机器学习\GitRepository\learnergy\learnergy\models\gaussian\gaussian_rbm.py", line 214, in fit
    samples = samples.cuda()
RuntimeError: CUDA error: device-side assert triggered

But when I use CPU, the error would be:
 12%|█▏        | 55/469 [00:01<00:12, 31.99it/s]
Traceback (most recent call last):
  File "E:\Document\机器学习\GitRepository\learnergy\examples\applications\bernoulli\rbm_classification.py", line 43, in <module>
    model.fit(train, batch_size=batch_size, epochs=1)
  File "E:\Document\机器学习\GitRepository\learnergy\learnergy\models\gaussian\gaussian_rbm.py", line 217, in fit
    _, _, _, _, visible_states = self.gibbs_sampling(samples)
  File "E:\Document\机器学习\GitRepository\learnergy\learnergy\models\bernoulli\rbm.py", line 348, in gibbs_sampling
    pos_hidden_probs, pos_hidden_states = self.hidden_sampling(v)
  File "E:\Document\机器学习\GitRepository\learnergy\learnergy\models\bernoulli\rbm.py", line 296, in hidden_sampling
    states = torch.bernoulli(probs)
RuntimeError: Expected p_in >= 0 && p_in <= 1 to be true, but got false.  (Could this error message be improved?  If so, please report an enhancement request to PyTorch.)

It seems something went wrong when use torch.bernoulli to get the state in hidden_sampling, but I can't address this problem by myself.

In addition, I let the num_worker=0 when use the DataLoader in rbm_classification.py, such as:
train_batch = DataLoader(train, batch_size=batch_size, shuffle=False, num_workers=0)
val_batch = DataLoader(test, batch_size=10000, shuffle=False, num_workers=0)
if not,  'RuntimeError: DataLoader worker (pid(s) 2568) exited unexpectedly ' will be raised.
I hope this modify would not lead the errors mentioned above.

Waiting for your reply.

Best regards,
kyyongh.

**Comment by kyyongh** [comment]
Hi Mateus, thank you for replying.

I was running the rbm_classification.py with only change the model to GaussianRBM, keeping the initialization parameters same as the RBM：
model = GaussianRBM(
n_visible=784,
n_hidden=128,
steps=1,
learning_rate=0.1,
momentum=0,
decay=0,
temperature=1,
use_gpu=True,
)
and the above mentioned error occurred.

when I use GPU, the error woud be:
C:/cb/pytorch_1000000000000/work/aten/src\ATen/native/cuda/DistributionTemplates.h:591: block: [5,0,0], thread: [316,0,0] Assertion&nbsp;0 <= p4 &amp;&amp; p4 <= 1&nbsp;failed.
C:/cb/pytorch_1000000000000/work/aten/src\ATen/native/cuda/DistributionTemplates.h:591: block: [5,0,0], thread: [317,0,0] Assertion&nbsp;0 <= p4 &amp;&amp; p4 <= 1&nbsp;failed.
C:/cb/pytorch_1000000000000/work/aten/src\ATen/native/cuda/DistributionTemplates.h:591: block: [5,0,0], thread: [318,0,0] Assertion&nbsp;0 <= p4 &amp;&amp; p4 <= 1&nbsp;failed.
C:/cb/pytorch_1000000000000/work/aten/src\ATen/native/cuda/DistributionTemplates.h:591: block: [5,0,0], thread: [319,0,0] Assertion&nbsp;0 <= p4 &amp;&amp; p4 <= 1&nbsp;failed.
12%|█▏ | 56/469 [00:02<00:16, 25.34it/s]
Traceback (most recent call last):
File "E:\Document\机器学习\GitRepository\learnergy\examples\applications\bernoulli\rbm_classification.py", line 43, in
model.fit(train, batch_size=batch_size, epochs=1)
File "E:\Document\机器学习\GitRepository\learnergy\learnergy\models\gaussian\gaussian_rbm.py", line 214, in fit
samples = samples.cuda()
RuntimeError: CUDA error: device-side assert triggered

But when I use CPU, the error would be:
12%|█▏ | 55/469 [00:01<00:12, 31.99it/s]
Traceback (most recent call last):
File "E:\Document\机器学习\GitRepository\learnergy\examples\applications\bernoulli\rbm_classification.py", line 43, in
model.fit(train, batch_size=batch_size, epochs=1)
File "E:\Document\机器学习\GitRepository\learnergy\learnergy\models\gaussian\gaussian_rbm.py", line 217, in fit
_, _, _, _, visible_states = self.gibbs_sampling(samples)
File "E:\Document\机器学习\GitRepository\learnergy\learnergy\models\bernoulli\rbm.py", line 348, in gibbs_sampling
pos_hidden_probs, pos_hidden_states = self.hidden_sampling(v)
File "E:\Document\机器学习\GitRepository\learnergy\learnergy\models\bernoulli\rbm.py", line 296, in hidden_sampling
states = torch.bernoulli(probs)
RuntimeError: Expected p_in &gt;= 0 &amp;&amp; p_in <= 1 to be true, but got false. (Could this error message be improved? If so, please report an enhancement request to PyTorch.)

It seems something went wrong when use torch.bernoulli to get the state in hidden_sampling, but I can't address this problem by myself.

In addition, I let the num_worker=0 when use the DataLoader in rbm_classification.py, such as:
train_batch = DataLoader(train, batch_size=batch_size, shuffle=False, num_workers=0)
val_batch = DataLoader(test, batch_size=10000, shuffle=False, num_workers=0)
if not, 'RuntimeError: DataLoader worker (pid(s) 2568) exited unexpectedly ' will be raised.
I hope this modify would not lead the errors mentioned above.

Waiting for your reply.

Best regards,
kyyongh.



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "gugarosa/learnergy"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月15日(星期五) 晚上11:53
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [gugarosa/learnergy] probability bug (Issue #15)





 
Hello kyyongh,I hope is everything well with you.
 
Without knowing what is your initialization setup may be difficult to track such an issue.
 Even if the lack of additional information, seems that it is something wrong with the temperature parameter (T).
 However, if you can attach additional information about the running parameters, we can search the problem.
 
Best regards,
 Mateus.

**Comment by MateusRoder** [comment]
Hello @kyyongh.
Thanks for your additional information. I am going to check the GaussianRBM code and re-test it.

In addition, I would like to suggest one experimentation to you. I guess that you are running the GaussianRBM on MNIST, right?! Just to our sanity, lower the learning rate to 0.01, or less, just to check if it is not exploding in some way the hidden activation (like NaN values in case of the gradient explodes).

I wait your reply about this little parameter modification, while I keep searching some bug by this side.

Best regards,
Mateus Roder.

**Comment by kyyongh** [comment]
Hello Mateus.
Thanks for your suggestion. After trying lower the learning rate equal or less than 0.01, the gradient explodes won't be raised when I running the GaussianRBM on MNIST.


And there is one more thing I want to figure out.&nbsp;


I've find some others code about RBM, most of them choose to update parameters manually instead of using nn.Module just like the theory that&nbsp;Hinton introduced in his paper. In this way, the loss function is log likelihood, and the gradient comes from the derivative of the log likelihood. For example, when updating weights, they use CD algorithm to approximate the gradient of parameters, then update parameters just like&nbsp; &nbsp;w += learning_rate * Δw.&nbsp;


But I've also noticed, in learnergy, you used the optimizer of PyTorch to calculate the gradient of energy loss.&nbsp;What I'm curious about is, are these two ways equivalent? How does CD work when using&nbsp;optimizer of PyTorch. z


Thank you for your generosity. And I'm always waiting for your reply.


Best regards,
kyyongh.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "gugarosa/learnergy"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月16日(星期六) 晚上9:25
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [gugarosa/learnergy] probability bug (Issue #15)





 
Hello @kyyongh.
 Thanks for your additional information. I am going to check the GaussianRBM code and re-test it.
 
In addition, I would like to suggest one experimentation to you. I guess that you are running the GaussianRBM on MNIST, right?! Just to our sanity, lower the learning rate to 0.01, or less, just to check if it is not exploding in some way the hidden activation (like NaN values in case of the gradient explodes).
 
I wait your reply about this little parameter modification, while I keep searching some bug by this side.
 
Best regards,
 Mateus Roder.
